fix: puzzle transition
unjs/website pull request #57
Opened 2023-08-18 10:35 UTC by enkot

### 🔗 Linked issue

https://github.com/unjs/website/issues/37

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Simplified https://github.com/unjs/website/blob/main/components/puzzle/Puzzle.vue, removed magic numbers.
- Use `mouseenter` and `mouseleave` events on absolutely positioned div to remove "doom flickers" (https://www.joshwcomeau.com/animation/css-transitions/#doom-flicker-13)
- Moved to transforms for better performance.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-08-18 11:55 UTC, Barbapapazes requested changes

2023-08-18 11:55 UTC, Barbapapazes commented on components/puzzle/Puzzle.vue
> +    <div flex="~ col" space-y--9 :class="triggered ? 'drop-shadow-xl' : 'drop-shadow-md'">
I think we need a transition on this.

2023-08-18 11:56 UTC, Barbapapazes commented
It's very cleaver to use a fixed square for handling the hover! And love the refactor 💛

2023-08-18 12:00 UTC, Barbapapazes commented on components/puzzle/Puzzle.vue
> +    <div absolute inset-0 @mouseenter="triggered = true" @mouseleave="triggered = false" />
Couldn't we have a `peer` selector (moving the absolute before the puzzle ? https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state

2023-08-18 12:03 UTC, Barbapapazes commented
On lg screen, you need to move the away part a little to the right!

![image](https://github.com/unjs/website/assets/45267552/780875d0-6bf1-4c62-bd16-4458cb73aa09)

2023-08-19 09:49 UTC, enkot commented
@Barbapapazes Made it work with `group-hover`, `pointer-events-none` on child div did the trick :)

2023-08-19 14:51 UTC, Barbapapazes commented
> @Barbapapazes Made it work with `group-hover`, `pointer-events-none` on child div did the trick :)

oh niiice!

2023-08-19 14:52 UTC, Barbapapazes approved these changes
Looks perfect! Thank you so much for this!

2023-08-19 14:54 UTC, merged